<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\{DB, Hash};

class SpkKprSeeder extends Seeder
{
    public function run(): void
    {
        // ==================== PENGATURAN ====================
        DB::table('pengaturan')->insert([
            ['kunci' => 'threshold_layak', 'nilai' => '60', 'keterangan' => 'Batas minimum skor SMART untuk dinyatakan layak'],
            ['kunci' => 'threshold_layak_bersyarat', 'nilai' => '50', 'keterangan' => 'Batas minimum skor SMART untuk layak bersyarat'],
            ['kunci' => 'dp_minimum_persen', 'nilai' => '10', 'keterangan' => 'Persentase DP minimum'],
            ['kunci' => 'tenor_maksimum_tahun', 'nilai' => '20', 'keterangan' => 'Tenor KPR maksimum dalam tahun'],
            ['kunci' => 'rasio_cicilan_maksimum', 'nilai' => '40', 'keterangan' => 'Rasio maksimum cicilan terhadap penghasilan (%)'],
            ['kunci' => 'nama_perusahaan', 'nilai' => 'PT Citra Pasada Properti', 'keterangan' => 'Nama perusahaan'],
            ['kunci' => 'versi_aplikasi', 'nilai' => '1.0.0', 'keterangan' => 'Versi sistem SPK KPR'],
        ]);

        // ==================== KRITERIA ====================
        DB::table('kriteria')->insert([
            ['kode_kriteria' => 'C1', 'nama_kriteria' => 'Penghasilan bersih per bulan', 'deskripsi' => 'Total penghasilan debitur setelah dikurangi pengeluaran rutin. Semakin besar semakin baik.', 'tipe' => 'benefit', 'bobot' => 0.2500, 'satuan' => 'Rupiah', 'nilai_min' => 3000000, 'nilai_max' => 20000000, 'urutan' => 1, 'aktif' => true],
            ['kode_kriteria' => 'C2', 'nama_kriteria' => 'Rasio cicilan terhadap penghasilan', 'deskripsi' => 'Persentase total cicilan dibanding penghasilan. Semakin kecil semakin baik.', 'tipe' => 'cost', 'bobot' => 0.2000, 'satuan' => 'Persen', 'nilai_min' => 10, 'nilai_max' => 70, 'urutan' => 2, 'aktif' => true],
            ['kode_kriteria' => 'C3', 'nama_kriteria' => 'Riwayat kredit (SLIK OJK)', 'deskripsi' => 'Status kolektibilitas kredit debitur. Semakin lancar semakin baik.', 'tipe' => 'benefit', 'bobot' => 0.2000, 'satuan' => 'Skor', 'nilai_min' => 1, 'nilai_max' => 5, 'urutan' => 3, 'aktif' => true],
            ['kode_kriteria' => 'C4', 'nama_kriteria' => 'Lama bekerja / menjalankan usaha', 'deskripsi' => 'Durasi pekerjaan atau usaha dalam tahun. Semakin lama semakin stabil.', 'tipe' => 'benefit', 'bobot' => 0.1500, 'satuan' => 'Tahun', 'nilai_min' => 0, 'nilai_max' => 15, 'urutan' => 4, 'aktif' => true],
            ['kode_kriteria' => 'C5', 'nama_kriteria' => 'Nilai agunan (properti yang diajukan)', 'deskripsi' => 'Nilai properti yang dijadikan jaminan KPR.', 'tipe' => 'benefit', 'bobot' => 0.1000, 'satuan' => 'Rupiah', 'nilai_min' => 100000000, 'nilai_max' => 2000000000, 'urutan' => 5, 'aktif' => true],
            ['kode_kriteria' => 'C6', 'nama_kriteria' => 'Jumlah tanggungan', 'deskripsi' => 'Jumlah anggota keluarga yang menjadi tanggungan. Semakin sedikit semakin baik.', 'tipe' => 'cost', 'bobot' => 0.1000, 'satuan' => 'Orang', 'nilai_min' => 0, 'nilai_max' => 6, 'urutan' => 6, 'aktif' => true],
        ]);

        // ==================== KRITERIA SKALA ====================
        DB::table('kriteria_skala')->insert([
            // Penghasilan (C1)
            ['kriteria_id'=>1,'skor'=>1,'keterangan'=>'Penghasilan < Rp 3 juta','nilai_min'=>0,'nilai_max'=>2999999],
            ['kriteria_id'=>1,'skor'=>2,'keterangan'=>'Penghasilan Rp 3 – 5 juta','nilai_min'=>3000000,'nilai_max'=>4999999],
            ['kriteria_id'=>1,'skor'=>3,'keterangan'=>'Penghasilan Rp 5 – 8 juta','nilai_min'=>5000000,'nilai_max'=>7999999],
            ['kriteria_id'=>1,'skor'=>4,'keterangan'=>'Penghasilan Rp 8 – 12 juta','nilai_min'=>8000000,'nilai_max'=>11999999],
            ['kriteria_id'=>1,'skor'=>5,'keterangan'=>'Penghasilan > Rp 12 juta','nilai_min'=>12000000,'nilai_max'=>99999999],
            // Rasio cicilan (C2)
            ['kriteria_id'=>2,'skor'=>5,'keterangan'=>'Rasio ≤ 20%','nilai_min'=>0,'nilai_max'=>20],
            ['kriteria_id'=>2,'skor'=>4,'keterangan'=>'Rasio 21–30%','nilai_min'=>21,'nilai_max'=>30],
            ['kriteria_id'=>2,'skor'=>3,'keterangan'=>'Rasio 31–40%','nilai_min'=>31,'nilai_max'=>40],
            ['kriteria_id'=>2,'skor'=>2,'keterangan'=>'Rasio 41–50%','nilai_min'=>41,'nilai_max'=>50],
            ['kriteria_id'=>2,'skor'=>1,'keterangan'=>'Rasio > 50%','nilai_min'=>51,'nilai_max'=>100],
            // Riwayat kredit (C3)
            ['kriteria_id'=>3,'skor'=>5,'keterangan'=>'Kol. 1 — Lancar','nilai_min'=>5,'nilai_max'=>5],
            ['kriteria_id'=>3,'skor'=>4,'keterangan'=>'Kol. 2 — Dalam perhatian khusus','nilai_min'=>4,'nilai_max'=>4],
            ['kriteria_id'=>3,'skor'=>3,'keterangan'=>'Kol. 3 — Kurang lancar (sudah lunas)','nilai_min'=>3,'nilai_max'=>3],
            ['kriteria_id'=>3,'skor'=>2,'keterangan'=>'Kol. 4 — Diragukan','nilai_min'=>2,'nilai_max'=>2],
            ['kriteria_id'=>3,'skor'=>1,'keterangan'=>'Kol. 5 — Macet / blacklist','nilai_min'=>1,'nilai_max'=>1],
            // Lama bekerja (C4)
            ['kriteria_id'=>4,'skor'=>1,'keterangan'=>'Lama bekerja < 1 tahun','nilai_min'=>0,'nilai_max'=>0],
            ['kriteria_id'=>4,'skor'=>2,'keterangan'=>'Lama bekerja 1–2 tahun','nilai_min'=>1,'nilai_max'=>2],
            ['kriteria_id'=>4,'skor'=>3,'keterangan'=>'Lama bekerja 2–5 tahun','nilai_min'=>2,'nilai_max'=>5],
            ['kriteria_id'=>4,'skor'=>4,'keterangan'=>'Lama bekerja 5–10 tahun','nilai_min'=>5,'nilai_max'=>10],
            ['kriteria_id'=>4,'skor'=>5,'keterangan'=>'Lama bekerja > 10 tahun','nilai_min'=>10,'nilai_max'=>99],
            // Nilai agunan (C5)
            ['kriteria_id'=>5,'skor'=>1,'keterangan'=>'Agunan < Rp 100 juta','nilai_min'=>0,'nilai_max'=>99999999],
            ['kriteria_id'=>5,'skor'=>2,'keterangan'=>'Agunan Rp 100 – 250 juta','nilai_min'=>100000000,'nilai_max'=>249999999],
            ['kriteria_id'=>5,'skor'=>3,'keterangan'=>'Agunan Rp 250 – 500 juta','nilai_min'=>250000000,'nilai_max'=>499999999],
            ['kriteria_id'=>5,'skor'=>4,'keterangan'=>'Agunan Rp 500 juta – 1 miliar','nilai_min'=>500000000,'nilai_max'=>999999999],
            ['kriteria_id'=>5,'skor'=>5,'keterangan'=>'Agunan > Rp 1 miliar','nilai_min'=>1000000000,'nilai_max'=>9999999999],
            // Jumlah tanggungan (C6)
            ['kriteria_id'=>6,'skor'=>5,'keterangan'=>'Tidak ada tanggungan (0)','nilai_min'=>0,'nilai_max'=>0],
            ['kriteria_id'=>6,'skor'=>4,'keterangan'=>'1 tanggungan','nilai_min'=>1,'nilai_max'=>1],
            ['kriteria_id'=>6,'skor'=>3,'keterangan'=>'2 tanggungan','nilai_min'=>2,'nilai_max'=>2],
            ['kriteria_id'=>6,'skor'=>2,'keterangan'=>'3 tanggungan','nilai_min'=>3,'nilai_max'=>3],
            ['kriteria_id'=>6,'skor'=>1,'keterangan'=>'≥ 4 tanggungan','nilai_min'=>4,'nilai_max'=>99],
        ]);

        // ==================== PROYEK ====================
        DB::table('proyek')->insert([
            ['kode_proyek'=>'PRJ-001','nama_proyek'=>'Cluster Melati','lokasi'=>'Jl. Melati Raya No. 1, Bojonggede','kota'=>'Bogor','provinsi'=>'Jawa Barat','deskripsi'=>'Perumahan eksklusif dengan konsep hijau','status'=>'aktif', 'foto_proyek' => '["proyek1_1.jpg", "proyek1_2.jpg"]'],
            ['kode_proyek'=>'PRJ-002','nama_proyek'=>'Cluster Anggrek','lokasi'=>'Jl. Anggrek Indah No. 5, Citayam','kota'=>'Bogor','provinsi'=>'Jawa Barat','deskripsi'=>'Lokasi strategis dekat pusat kota','status'=>'aktif', 'foto_proyek' => '["proyek2_1.jpg", "proyek2_2.jpg"]'],
            ['kode_proyek'=>'PRJ-003','nama_proyek'=>'Cluster Mawar','lokasi'=>'Jl. Mawar Blok A, Parung','kota'=>'Bogor','provinsi'=>'Jawa Barat','deskripsi'=>'Area tenang dan asri','status'=>'aktif', 'foto_proyek' => '["proyek3_1.jpg", "proyek3_2.jpg"]'],
            ['kode_proyek'=>'PRJ-004','nama_proyek'=>'Cluster Dahlia','lokasi'=>'Jl. Dahlia Permai, Sawangan','kota'=>'Depok','provinsi'=>'Jawa Barat','deskripsi'=>'Akses mudah ke tol','status'=>'aktif', 'foto_proyek' => '["proyek4_1.jpg", "proyek4_2.jpg"]'],
        ]);

        // ==================== TIPE UNIT ====================
        DB::table('tipe_unit')->insert([
            ['proyek_id'=>1,'kode_tipe'=>'T36-72','nama_tipe'=>'Tipe 36/72','luas_tanah'=>72,'luas_bangunan'=>36,'jumlah_kamar'=>2,'jumlah_wc'=>1,'harga'=>450000000,'stok_tersedia'=>18, 'gambar' => '["tipe36-72_1.jpg", "tipe36-72_2.jpg"]'],
            ['proyek_id'=>1,'kode_tipe'=>'T45-90','nama_tipe'=>'Tipe 45/90','luas_tanah'=>90,'luas_bangunan'=>45,'jumlah_kamar'=>3,'jumlah_wc'=>2,'harga'=>595000000,'stok_tersedia'=>10, 'gambar' => '["tipe45-90_1.jpg", "tipe45-90_2.jpg"]'],
            ['proyek_id'=>2,'kode_tipe'=>'T45-90','nama_tipe'=>'Tipe 45/90','luas_tanah'=>90,'luas_bangunan'=>45,'jumlah_kamar'=>3,'jumlah_wc'=>2,'harga'=>615000000,'stok_tersedia'=>12, 'gambar' => '["tipe45-90_1.jpg", "tipe45-90_2.jpg"]'],
            ['proyek_id'=>2,'kode_tipe'=>'T54-108','nama_tipe'=>'Tipe 54/108','luas_tanah'=>108,'luas_bangunan'=>54,'jumlah_kamar'=>3,'jumlah_wc'=>2,'harga'=>750000000,'stok_tersedia'=>8, 'gambar' => '["tipe54-108_1.jpg", "tipe54-108_2.jpg"]'],
            ['proyek_id'=>3,'kode_tipe'=>'T54-108','nama_tipe'=>'Tipe 54/108','luas_tanah'=>108,'luas_bangunan'=>54,'jumlah_kamar'=>3,'jumlah_wc'=>2,'harga'=>790000000,'stok_tersedia'=>6, 'gambar' => '["tipe54-108_1.jpg", "tipe54-108_2.jpg"]'],
            ['proyek_id'=>3,'kode_tipe'=>'T60-120','nama_tipe'=>'Tipe 60/120','luas_tanah'=>120,'luas_bangunan'=>60,'jumlah_kamar'=>4,'jumlah_wc'=>3,'harga'=>980000000,'stok_tersedia'=>4, 'gambar' => '["tipe60-120_1.jpg", "tipe60-120_2.jpg"]'],
            ['proyek_id'=>4,'kode_tipe'=>'T60-120','nama_tipe'=>'Tipe 60/120','luas_tanah'=>120,'luas_bangunan'=>60,'jumlah_kamar'=>4,'jumlah_wc'=>3,'harga'=>1050000000,'stok_tersedia'=>5, 'gambar' => '["tipe60-120_1.jpg", "tipe60-120_2.jpg"]'],
            ['proyek_id'=>4,'kode_tipe'=>'T72-144','nama_tipe'=>'Tipe 72/144','luas_tanah'=>144,'luas_bangunan'=>72,'jumlah_kamar'=>4,'jumlah_wc'=>3,'harga'=>1350000000,'stok_tersedia'=>3, 'gambar' => '["tipe72-144_1.jpg", "tipe72-144_2.jpg"]'],
        ]);

        // ==================== UNIT ====================
        DB::table('unit')->insert([
            ['tipe_unit_id'=>1,'kode_unit'=>'U-001','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>1,'kode_unit'=>'U-002','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>1,'kode_unit'=>'U-003','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>2,'kode_unit'=>'U-004','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>2,'kode_unit'=>'U-005','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>3,'kode_unit'=>'U-006','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>3,'kode_unit'=>'U-007','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>4,'kode_unit'=>'U-008','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>4,'kode_unit'=>'U-009','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>5,'kode_unit'=>'U-010','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>5,'kode_unit'=>'U-011','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>6,'kode_unit'=>'U-012','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>7,'kode_unit'=>'U-013','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
            ['tipe_unit_id'=>8,'kode_unit'=>'U-014','status'=>'tersedia', 'foto_unit' => '["foto1.jpg", "foto2.jpg", "foto3.jpg"]', 'fasilitas' => '["Listrik 1300 watt", "Air PDAM", "Carport", "Kamar mandi dalam", "Kamar tidur utama dengan AC"]'],
        ]);

        // ==================== USERS ====================
        DB::table('users')->insert([
            // Debitur
            ['nama_lengkap'=>'Budi Santoso','email'=>'budi.santoso@email.com','password'=>Hash::make('Password123!'),'role'=>'debitur','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            ['nama_lengkap'=>'Sari Dewi','email'=>'sari.dewi@email.com','password'=>Hash::make('Password123!'),'role'=>'debitur','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            ['nama_lengkap'=>'Ahmad Fauzi','email'=>'ahmad.fauzi@email.com','password'=>Hash::make('Password123!'),'role'=>'debitur','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            ['nama_lengkap'=>'Rina Kartika','email'=>'rina.kartika@email.com','password'=>Hash::make('Password123!'),'role'=>'debitur','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            // Marketing
            ['nama_lengkap'=>'Rina Wijaya','email'=>'rina.wijaya@cipp.co.id','password'=>Hash::make('Password123!'),'role'=>'marketing','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            ['nama_lengkap'=>'Dedi Kurniawan','email'=>'dedi.kurniawan@cipp.co.id','password'=>Hash::make('Password123!'),'role'=>'marketing','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            // Admin
            ['nama_lengkap'=>'Sri Mulyani','email'=>'sri.mulyani@cipp.co.id','password'=>Hash::make('Password123!'),'role'=>'admin','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
            // Manajer
            ['nama_lengkap'=>'Hendra Susanto','email'=>'hendra.susanto@cipp.co.id','password'=>Hash::make('Password123!'),'role'=>'manajer','status'=>'aktif','last_login'=>null,'foto_profil'=>null],
        ]);

        // ==================== DEBITUR PRIBADI ====================
        DB::table('debitur_pribadi')->insert([
            [
                'user_id'=>1,
                'nik'=>'3271010101900001',
                'tempat_lahir'=>'Jakarta',
                'tanggal_lahir'=>'1990-01-01',
                'jenis_kelamin'=>'L',
                'agama'=>'Islam',
                'status_pernikahan'=>'menikah',
                'jumlah_tanggungan'=>2,
                'pendidikan_terakhir'=>'S1',
                'kewarganegaraan'=>'WNI',
                'nama_ibu_kandung'=>'Siti Aminah',
                'no_kk'=>'3271010101010001',
                'nama_pasangan'=>'Dewi Lestari',
                'nik_pasangan'=>'3271010101900002',
                'alamat_ktp'=>'Jl. Melati Raya No. 10, Bojonggede',
                'rt_rw'=>'01/01',
                'kelurahan'=>'Bojonggede',
                'kecamatan'=>'Bojonggede',
                'kota'=>'Bogor',
                'provinsi'=>'Jawa Barat',
                'kode_pos'=>'16920',
                'status_tempat_tinggal'=>'milik_sendiri',
                'no_telepon'=>'0211234567',
                'no_hp'=>'081234567890',
                'email_aktif'=>'budi@email.com',
                'pas_foto'=>null,
            ],
            [
                'user_id'=>2,
                'nik'=>'3271020202900002',
                'tempat_lahir'=>'Bandung',
                'tanggal_lahir'=>'1992-02-02',
                'jenis_kelamin'=>'P',
                'agama'=>'Islam',
                'status_pernikahan'=>'menikah',
                'jumlah_tanggungan'=>3,
                'pendidikan_terakhir'=>'S1',
                'kewarganegaraan'=>'WNI',
                'nama_ibu_kandung'=>'Nurhayati',
                'no_kk'=>'3271020202020002',
                'nama_pasangan'=>'Andi Prasetyo',
                'nik_pasangan'=>'3271020202900003',
                'alamat_ktp'=>'Jl. Anggrek Indah No. 20, Citayam',
                'rt_rw'=>'02/02',
                'kelurahan'=>'Citayam',
                'kecamatan'=>'Bojonggede',
                'kota'=>'Bogor',
                'provinsi'=>'Jawa Barat',
                'kode_pos'=>'16920',
                'status_tempat_tinggal'=>'milik_sendiri',
                'no_telepon'=>'0212345678',
                'no_hp'=>'082345678901',
                'email_aktif'=>'sari@email.com',
                'pas_foto'=>null,
            ],
            [
                'user_id'=>3,
                'nik'=>'3271030303900003',
                'tempat_lahir'=>'Bogor',
                'tanggal_lahir'=>'1990-03-03',
                'jenis_kelamin'=>'L',
                'agama'=>'Islam',
                'status_pernikahan'=>'menikah',
                'jumlah_tanggungan'=>1,
                'pendidikan_terakhir'=>'S2',
                'kewarganegaraan'=>'WNI',
                'nama_ibu_kandung'=>'Kartini',
                'no_kk'=>'3271030303030003',
                'nama_pasangan'=>'Fitri Handayani',
                'nik_pasangan'=>'3271030303900004',
                'alamat_ktp'=>'Jl. Mawar Blok B No. 5, Parung',
                'rt_rw'=>'03/03',
                'kelurahan'=>'Parung',
                'kecamatan'=>'Parung',
                'kota'=>'Bogor',
                'provinsi'=>'Jawa Barat',
                'kode_pos'=>'16330',
                'status_tempat_tinggal'=>'milik_sendiri',
                'no_telepon'=>'0213456789',
                'no_hp'=>'083456789012',
                'email_aktif'=>'ahmad@email.com',
                'pas_foto'=>null,
            ],
            [
                'user_id'=>4,
                'nik'=>'3271040404900004',
                'tempat_lahir'=>'Depok',
                'tanggal_lahir'=>'1994-04-04',
                'jenis_kelamin'=>'P',
                'agama'=>'Kristen',
                'status_pernikahan'=>'belum_menikah',
                'jumlah_tanggungan'=>4,
                'pendidikan_terakhir'=>'S1',
                'kewarganegaraan'=>'WNI',
                'nama_ibu_kandung'=>'Marlina',
                'no_kk'=>'3271040404040004',
                'nama_pasangan'=>null,
                'nik_pasangan'=>null,
                'alamat_ktp'=>'Jl. Dahlia Permai No. 15, Sawangan',
                'rt_rw'=>'04/04',
                'kelurahan'=>'Sawangan',
                'kecamatan'=>'Sawangan',
                'kota'=>'Depok',
                'provinsi'=>'Jawa Barat',
                'kode_pos'=>'16511',
                'status_tempat_tinggal'=>'keluarga',
                'no_telepon'=>'0214567890',
                'no_hp'=>'084567890123',
                'email_aktif'=>'rina@email.com',
                'pas_foto'=>null,
            ],
        ]);

        // ==================== DEBITUR PEKERJAAN ====================
        DB::table('debitur_pekerjaan')->insert([
            [
                'user_id'=>1,
                'status_pekerjaan'=>'karyawan_swasta',
                'nama_perusahaan'=>'PT Maju Jaya',
                'bidang_usaha'=>'Teknologi',
                'jabatan'=>'Staff IT',
                'status_kepegawaian'=>'tetap',
                'lama_bekerja_tahun'=>5,
                'lama_bekerja_bulan'=>0,
                'alamat_perusahaan'=>'Jl. Melati Raya No. 10, Bojonggede',
                'kota_perusahaan'=>'Bogor',
                'telp_perusahaan'=>'021-1234567',
                'npwp'=>'01.234.567.8-901.000',
                'penghasilan_pokok'=>7000000,
                'tunjangan_tetap'=>500000,
                'penghasilan_lain'=>500000,
            ],
            [
                'user_id'=>2,
                'status_pekerjaan'=>'wiraswasta',
                'nama_perusahaan'=>'CV Sukses Selalu',
                'bidang_usaha'=>'Perdagangan',
                'jabatan'=>'Pemilik',
                'status_kepegawaian'=>'pemilik',
                'lama_bekerja_tahun'=>3,
                'lama_bekerja_bulan'=>0,
                'alamat_perusahaan'=>'Jl. Anggrek Indah No. 20, Citayam',
                'kota_perusahaan'=>'Bogor',
                'telp_perusahaan'=>'021-2345678',
                'npwp'=>'02.345.678.9-012.000',
                'penghasilan_pokok'=>10000000,
                'tunjangan_tetap'=>0,
                'penghasilan_lain'=>2000000,
            ],
            [
                'user_id'=>3,
                'status_pekerjaan'=>'pns',
                'nama_perusahaan'=>'Dinas Pendidikan Kabupaten Bogor',
                'bidang_usaha'=>'Pemerintahan',
                'jabatan'=>'Guru',
                'status_kepegawaian'=>'tetap',
                'lama_bekerja_tahun'=>10,
                'lama_bekerja_bulan'=>0,
                'alamat_perusahaan'=>'Jl. Raya Pajajaran No. 1, Bogor',
                'kota_perusahaan'=>'Bogor',
                'telp_perusahaan'=>'0251-1234567',
                'npwp'=>'03.456.789.0-123.000',
                'penghasilan_pokok'=>12000000,
                'tunjangan_tetap'=>2000000,
                'penghasilan_lain'=>1000000,
            ],
            [
                'user_id'=>4,
                'status_pekerjaan'=>'karyawan_swasta',
                'nama_perusahaan'=>'PT Sejahtera Abadi',
                'bidang_usaha'=>'Manufaktur',
                'jabatan'=>'Staff Administrasi',
                'status_kepegawaian'=>'kontrak',
                'lama_bekerja_tahun'=>2,
                'lama_bekerja_bulan'=>0,
                'alamat_perusahaan'=>'Jl. Dahlia Permai No. 15, Sawangan',
                'kota_perusahaan'=>'Depok',
                'telp_perusahaan'=>'021-3456789',
                'npwp'=>'04.567.890.1-234.000',
                'penghasilan_pokok'=>5000000,
                'tunjangan_tetap'=>500000,
                'penghasilan_lain'=>500000,
            ],
        ]);

        // ==================== DEBITUR KEUANGAN ====================
        DB::table('debitur_keuangan')->insert([
            [
                'user_id'=>1,
                'nama_bank'=>'Bank Mandiri',
                'nomor_rekening'=>'1234567890',
                'nama_pemilik_rekening'=>'Budi Santoso',
                'jenis_rekening'=>'tabungan',
                'rata_saldo_3bln'=>5000000,
                'rata_mutasi_kredit'=>8000000,
                'total_cicilan_perbulan'=>2000000,
                'jumlah_kredit_aktif'=>1,
                'limit_kartu_kredit'=>10000000,
                'tagihan_kartu_kredit'=>2000000,
                'memiliki_kpr_aktif'=>false,
                'sisa_pokok_kpr_aktif'=>0,
                'status_kredit'=>'lancar',
                'pernah_gagal_bayar'=>false,
                'aset_properti_lain'=>0,
                'aset_kendaraan'=>150000000,
                'aset_tabungan_deposito'=>25000000,
                'aset_investasi_lain'=>10000000,
                'rasio_cicilan'=>25.00,
            ],
            [
                'user_id'=>2,
                'nama_bank'=>'BCA',
                'nomor_rekening'=>'0987654321',
                'nama_pemilik_rekening'=>'Sari Dewi',
                'jenis_rekening'=>'giro',
                'rata_saldo_3bln'=>15000000,
                'rata_mutasi_kredit'=>12000000,
                'total_cicilan_perbulan'=>4200000,
                'jumlah_kredit_aktif'=>2,
                'limit_kartu_kredit'=>15000000,
                'tagihan_kartu_kredit'=>5000000,
                'memiliki_kpr_aktif'=>false,
                'sisa_pokok_kpr_aktif'=>0,
                'status_kredit'=>'lancar',
                'pernah_gagal_bayar'=>false,
                'aset_properti_lain'=>0,
                'aset_kendaraan'=>250000000,
                'aset_tabungan_deposito'=>50000000,
                'aset_investasi_lain'=>25000000,
                'rasio_cicilan'=>35.00,
            ],
            [
                'user_id'=>3,
                'nama_bank'=>'BNI',
                'nomor_rekening'=>'5555555555',
                'nama_pemilik_rekening'=>'Ahmad Fauzi',
                'jenis_rekening'=>'tabungan',
                'rata_saldo_3bln'=>25000000,
                'rata_mutasi_kredit'=>15000000,
                'total_cicilan_perbulan'=>3000000,
                'jumlah_kredit_aktif'=>1,
                'limit_kartu_kredit'=>20000000,
                'tagihan_kartu_kredit'=>3000000,
                'memiliki_kpr_aktif'=>true,
                'sisa_pokok_kpr_aktif'=>200000000,
                'status_kredit'=>'lancar',
                'pernah_gagal_bayar'=>false,
                'aset_properti_lain'=>500000000,
                'aset_kendaraan'=>350000000,
                'aset_tabungan_deposito'=>100000000,
                'aset_investasi_lain'=>50000000,
                'rasio_cicilan'=>20.00,
            ],
            [
                'user_id'=>4,
                'nama_bank'=>'BRI',
                'nomor_rekening'=>'4444444444',
                'nama_pemilik_rekening'=>'Rina Kartika',
                'jenis_rekening'=>'tabungan',
                'rata_saldo_3bln'=>2000000,
                'rata_mutasi_kredit'=>6000000,
                'total_cicilan_perbulan'=>2700000,
                'jumlah_kredit_aktif'=>2,
                'limit_kartu_kredit'=>5000000,
                'tagihan_kartu_kredit'=>4000000,
                'memiliki_kpr_aktif'=>false,
                'sisa_pokok_kpr_aktif'=>0,
                'status_kredit'=>'dpk',
                'pernah_gagal_bayar'=>false,
                'aset_properti_lain'=>0,
                'aset_kendaraan'=>100000000,
                'aset_tabungan_deposito'=>10000000,
                'aset_investasi_lain'=>0,
                'rasio_cicilan'=>45.00,
            ],
        ]);

        // ==================== PENGAJUAN ====================
        DB::table('pengajuan')->insert([
            [
                'kode_pengajuan'=>'KPR-2024-001',
                'user_id'=>1,
                'unit_id'=>1,
                'harga_properti'=>450000000,
                'uang_muka'=>45000000,
                'persen_dp'=>10.00,
                'jumlah_pinjaman'=>405000000,
                'tenor_tahun'=>15,
                'estimasi_angsuran'=>3500000,
                'rasio_angsuran'=>35.00,
                'tujuan_pembelian'=>'hunian_sendiri',
                'sumber_dp'=>'tabungan',
                'status'=>'submitted',
                'tgl_submitted'=>'2024-06-01 10:00:00',
                'tgl_marketing_proses'=>null,
                'tgl_admin_proses'=>null,
                'tgl_selesai'=>null,
                'marketing_id'=>null,
                'admin_id'=>null,
                'catatan_debitur'=>'Mengajukan KPR untuk rumah pertama',
            ],
            [
                'kode_pengajuan'=>'KPR-2024-002',
                'user_id'=>2,
                'unit_id'=>3,
                'harga_properti'=>615000000,
                'uang_muka'=>61500000,
                'persen_dp'=>10.00,
                'jumlah_pinjaman'=>553500000,
                'tenor_tahun'=>20,
                'estimasi_angsuran'=>4800000,
                'rasio_angsuran'=>32.00,
                'tujuan_pembelian'=>'hunian_sendiri',
                'sumber_dp'=>'tabungan',
                'status'=>'submitted',
                'tgl_submitted'=>'2024-06-02 11:30:00',
                'tgl_marketing_proses'=>null,
                'tgl_admin_proses'=>null,
                'tgl_selesai'=>null,
                'marketing_id'=>null,
                'admin_id'=>null,
                'catatan_debitur'=>'Proses cepat mohon dibantu',
            ],
            [
                'kode_pengajuan'=>'KPR-2024-003',
                'user_id'=>3,
                'unit_id'=>6,
                'harga_properti'=>980000000,
                'uang_muka'=>147000000,
                'persen_dp'=>15.00,
                'jumlah_pinjaman'=>833000000,
                'tenor_tahun'=>20,
                'estimasi_angsuran'=>7200000,
                'rasio_angsuran'=>40.00,
                'tujuan_pembelian'=>'investasi',
                'sumber_dp'=>'tabungan',
                'status'=>'submitted',
                'tgl_submitted'=>'2024-06-03 09:15:00',
                'tgl_marketing_proses'=>null,
                'tgl_admin_proses'=>null,
                'tgl_selesai'=>null,
                'marketing_id'=>null,
                'admin_id'=>null,
                'catatan_debitur'=>'Unit tipe 60/120 di Cluster Mawar',
            ],
            [
                'kode_pengajuan'=>'KPR-2024-004',
                'user_id'=>4,
                'unit_id'=>10,
                'harga_properti'=>1050000000,
                'uang_muka'=>157500000,
                'persen_dp'=>15.00,
                'jumlah_pinjaman'=>892500000,
                'tenor_tahun'=>15,
                'estimasi_angsuran'=>7800000,
                'rasio_angsuran'=>65.00,
                'tujuan_pembelian'=>'hunian_sendiri',
                'sumber_dp'=>'keluarga',
                'status'=>'submitted',
                'tgl_submitted'=>'2024-06-04 14:45:00',
                'tgl_marketing_proses'=>null,
                'tgl_admin_proses'=>null,
                'tgl_selesai'=>null,
                'marketing_id'=>null,
                'admin_id'=>null,
                'catatan_debitur'=>'Mohon segera diproses',
            ],
        ]);

        // ==================== VERIFIKASI MARKETING ====================
        DB::table('verifikasi_marketing')->insert([
            [
                'pengajuan_id'=>1,
                'marketing_id'=>5,
                'dok_ktp_valid'=>true,
                'dok_kk_valid'=>true,
                'dok_slip_gaji_valid'=>true,
                'dok_rek_koran_valid'=>true,
                'dok_slik_valid'=>true,
                'dok_surat_kerja_valid'=>true,
                'dok_npwp_valid'=>true,
                'tgl_kunjungan'=>'2024-06-05',
                'alamat_dikunjungi'=>'Jl. Melati Raya No. 10, Bojonggede',
                'kondisi_sesuai_data'=>true,
                'penghasilan_terverif'=>true,
                'catatan_lapangan'=>'Data valid, calon debitur kooperatif',
                'rekomendasi_marketing'=>'layak',
                'keputusan'=>'ajukan_ke_admin',
                'alasan_keputusan'=>'Data lengkap dan valid',
                'tgl_keputusan'=>'2024-06-05 15:00:00',
            ],
            [
                'pengajuan_id'=>2,
                'marketing_id'=>6,
                'dok_ktp_valid'=>true,
                'dok_kk_valid'=>true,
                'dok_slip_gaji_valid'=>true,
                'dok_rek_koran_valid'=>true,
                'dok_slik_valid'=>true,
                'dok_surat_kerja_valid'=>true,
                'dok_npwp_valid'=>true,
                'tgl_kunjungan'=>'2024-06-06',
                'alamat_dikunjungi'=>'Jl. Anggrek Indah No. 20, Citayam',
                'kondisi_sesuai_data'=>true,
                'penghasilan_terverif'=>true,
                'catatan_lapangan'=>'Usaha berjalan dengan baik',
                'rekomendasi_marketing'=>'layak',
                'keputusan'=>'ajukan_ke_admin',
                'alasan_keputusan'=>'Layak diproses',
                'tgl_keputusan'=>'2024-06-06 16:30:00',
            ],
            [
                'pengajuan_id'=>3,
                'marketing_id'=>5,
                'dok_ktp_valid'=>true,
                'dok_kk_valid'=>true,
                'dok_slip_gaji_valid'=>true,
                'dok_rek_koran_valid'=>true,
                'dok_slik_valid'=>true,
                'dok_surat_kerja_valid'=>true,
                'dok_npwp_valid'=>true,
                'tgl_kunjungan'=>'2024-06-07',
                'alamat_dikunjungi'=>'Jl. Mawar Blok B No. 5, Parung',
                'kondisi_sesuai_data'=>true,
                'penghasilan_terverif'=>true,
                'catatan_lapangan'=>'Debitur memiliki penghasilan stabil',
                'rekomendasi_marketing'=>'layak',
                'keputusan'=>'ajukan_ke_admin',
                'alasan_keputusan'=>'Data memenuhi syarat',
                'tgl_keputusan'=>'2024-06-07 10:45:00',
            ],
            [
                'pengajuan_id'=>4,
                'marketing_id'=>6,
                'dok_ktp_valid'=>true,
                'dok_kk_valid'=>false,
                'dok_slip_gaji_valid'=>true,
                'dok_rek_koran_valid'=>true,
                'dok_slik_valid'=>true,
                'dok_surat_kerja_valid'=>false,
                'dok_npwp_valid'=>false,
                'tgl_kunjungan'=>'2024-06-08',
                'alamat_dikunjungi'=>'Jl. Dahlia Permai No. 15, Sawangan',
                'kondisi_sesuai_data'=>true,
                'penghasilan_terverif'=>true,
                'catatan_lapangan'=>'Dokumen KK dan surat kerja belum lengkap',
                'rekomendasi_marketing'=>'perlu_pertimbangan',
                'keputusan'=>'minta_revisi',
                'alasan_keputusan'=>'Melengkapi dokumen yang kurang',
                'tgl_keputusan'=>'2024-06-08 14:15:00',
            ],
        ]);

        // ==================== PENILAIAN ====================
        DB::table('penilaian')->insert([
            [
                'pengajuan_id'=>1,
                'admin_id'=>7,
                'tgl_penilaian'=>'2024-06-06 09:00:00',
                'skor_akhir'=>48.50,
                'threshold'=>60.00,
                'hasil'=>null,
                'catatan_admin'=>'Menunggu perhitungan SMART',
            ],
            [
                'pengajuan_id'=>2,
                'admin_id'=>7,
                'tgl_penilaian'=>'2024-06-07 09:00:00',
                'skor_akhir'=>48.50,
                'threshold'=>60.00,
                'hasil'=>null,
                'catatan_admin'=>'Menunggu perhitungan SMART',
            ],
            [
                'pengajuan_id'=>3,
                'admin_id'=>7,
                'tgl_penilaian'=>'2024-06-08 09:00:00',
                'skor_akhir'=>48.50,
                'threshold'=>60.00,
                'hasil'=>null,
                'catatan_admin'=>'Menunggu perhitungan SMART',
            ],
        ]);

        // ==================== PENILAIAN DETAIL ====================
        DB::table('penilaian_detail')->insert([
            // Penilaian untuk pengajuan_id=1 (Budi Santoso)
            ['penilaian_id'=>1,'kriteria_id'=>1,'nilai_input'=>8000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>1,'kriteria_id'=>2,'nilai_input'=>25,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>1,'kriteria_id'=>3,'nilai_input'=>5,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>1,'kriteria_id'=>4,'nilai_input'=>5,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>1,'kriteria_id'=>5,'nilai_input'=>450000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>1,'kriteria_id'=>6,'nilai_input'=>2,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
            // Penilaian untuk pengajuan_id=2 (Sari Dewi)
            ['penilaian_id'=>2,'kriteria_id'=>1,'nilai_input'=>12000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>2,'kriteria_id'=>2,'nilai_input'=>35,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>2,'kriteria_id'=>3,'nilai_input'=>4,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>2,'kriteria_id'=>4,'nilai_input'=>3,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>2,'kriteria_id'=>5,'nilai_input'=>615000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>2,'kriteria_id'=>6,'nilai_input'=>3,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
            // Penilaian untuk pengajuan_id=3 (Ahmad Fauzi)
            ['penilaian_id'=>3,'kriteria_id'=>1,'nilai_input'=>15000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>3,'kriteria_id'=>2,'nilai_input'=>20,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>3,'kriteria_id'=>3,'nilai_input'=>5,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.2000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>3,'kriteria_id'=>4,'nilai_input'=>10,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1500,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>3,'kriteria_id'=>5,'nilai_input'=>980000000,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
            ['penilaian_id'=>3,'kriteria_id'=>6,'nilai_input'=>1,'nilai_normalisasi'=>0.0000,'bobot_snapshot'=>0.1000,'skor_kontribusi'=>0.0000],
        ]);

        // ==================== RIWAYAT STATUS ====================
        DB::table('riwayat_status')->insert([
            ['pengajuan_id'=>1,'status_lama'=>'draft','status_baru'=>'submitted','diubah_oleh'=>1,'keterangan'=>'Debitur mengajukan pengajuan','created_at'=>'2024-06-01 10:00:00'],
            ['pengajuan_id'=>1,'status_lama'=>'submitted','status_baru'=>'verifikasi_marketing','diubah_oleh'=>5,'keterangan'=>'Marketing mengambil antrian','created_at'=>'2024-06-02 08:00:00'],
            ['pengajuan_id'=>2,'status_lama'=>'draft','status_baru'=>'submitted','diubah_oleh'=>2,'keterangan'=>'Debitur mengajukan pengajuan','created_at'=>'2024-06-02 11:30:00'],
            ['pengajuan_id'=>2,'status_lama'=>'submitted','status_baru'=>'verifikasi_marketing','diubah_oleh'=>6,'keterangan'=>'Marketing mengambil antrian','created_at'=>'2024-06-03 08:00:00'],
            ['pengajuan_id'=>3,'status_lama'=>'draft','status_baru'=>'submitted','diubah_oleh'=>3,'keterangan'=>'Debitur mengajukan pengajuan','created_at'=>'2024-06-03 09:15:00'],
            ['pengajuan_id'=>3,'status_lama'=>'submitted','status_baru'=>'verifikasi_marketing','diubah_oleh'=>5,'keterangan'=>'Marketing mengambil antrian','created_at'=>'2024-06-04 08:00:00'],
            ['pengajuan_id'=>4,'status_lama'=>'draft','status_baru'=>'submitted','diubah_oleh'=>4,'keterangan'=>'Debitur mengajukan pengajuan','created_at'=>'2024-06-04 14:45:00'],
            ['pengajuan_id'=>4,'status_lama'=>'submitted','status_baru'=>'verifikasi_marketing','diubah_oleh'=>6,'keterangan'=>'Marketing mengambil antrian','created_at'=>'2024-06-05 08:00:00'],
        ]);

        // ==================== DOKUMEN PENGAJUAN ====================
        DB::table('dokumen_pengajuan')->insert([
            // Dokumen untuk pengajuan 1
            ['pengajuan_id'=>1,'jenis_dokumen'=>'ktp','nama_file'=>'KTP_Budi.pdf','path_file'=>'/dokumen/1/ktp.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-05 14:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>1,'jenis_dokumen'=>'kk','nama_file'=>'KK_Budi.pdf','path_file'=>'/dokumen/1/kk.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-05 14:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>1,'jenis_dokumen'=>'slip_gaji','nama_file'=>'Slip_Gaji_Budi.pdf','path_file'=>'/dokumen/1/slip_gaji.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-05 14:00:00','created_at'=>now(),'updated_at'=>now()],
            // Dokumen untuk pengajuan 2
            ['pengajuan_id'=>2,'jenis_dokumen'=>'ktp','nama_file'=>'KTP_Sari.pdf','path_file'=>'/dokumen/2/ktp.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>6,'tgl_diperiksa'=>'2024-06-06 15:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>2,'jenis_dokumen'=>'kk','nama_file'=>'KK_Sari.pdf','path_file'=>'/dokumen/2/kk.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>6,'tgl_diperiksa'=>'2024-06-06 15:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>2,'jenis_dokumen'=>'npwp','nama_file'=>'NPWP_Sari.pdf','path_file'=>'/dokumen/2/npwp.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>6,'tgl_diperiksa'=>'2024-06-06 15:00:00','created_at'=>now(),'updated_at'=>now()],
            // Dokumen untuk pengajuan 3
            ['pengajuan_id'=>3,'jenis_dokumen'=>'ktp','nama_file'=>'KTP_Ahmad.pdf','path_file'=>'/dokumen/3/ktp.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-07 10:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>3,'jenis_dokumen'=>'kk','nama_file'=>'KK_Ahmad.pdf','path_file'=>'/dokumen/3/kk.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-07 10:00:00','created_at'=>now(),'updated_at'=>now()],
            ['pengajuan_id'=>3,'jenis_dokumen'=>'slik_ojk','nama_file'=>'SLIK_Ahmad.pdf','path_file'=>'/dokumen/3/slik.pdf','ukuran_file'=>1024000,'mime_type'=>'application/pdf','status_verifikasi'=>'valid','catatan_verifikasi'=>null,'diperiksa_oleh'=>5,'tgl_diperiksa'=>'2024-06-07 10:00:00','created_at'=>now(),'updated_at'=>now()],
        ]);

        // ==================== NOTIFIKASI ====================
        DB::table('notifikasi')->insert([
            ['user_id'=>1,'pengajuan_id'=>1,'judul'=>'Pengajuan Disetujui Marketing','pesan'=>'Pengajuan KPR Anda telah diverifikasi oleh marketing dan diteruskan ke admin.','tipe'=>'sukses','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-05 15:00:00'],
            ['user_id'=>2,'pengajuan_id'=>2,'judul'=>'Pengajuan Disetujui Marketing','pesan'=>'Pengajuan KPR Anda telah diverifikasi oleh marketing dan diteruskan ke admin.','tipe'=>'sukses','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-06 16:30:00'],
            ['user_id'=>3,'pengajuan_id'=>3,'judul'=>'Pengajuan Disetujui Marketing','pesan'=>'Pengajuan KPR Anda telah diverifikasi oleh marketing dan diteruskan ke admin.','tipe'=>'sukses','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-07 10:45:00'],
            ['user_id'=>4,'pengajuan_id'=>4,'judul'=>'Dokumen Perlu Revisi','pesan'=>'Mohon lengkapi dokumen KK dan surat keterangan kerja untuk pengajuan KPR Anda.','tipe'=>'peringatan','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-08 14:15:00'],
            ['user_id'=>7,'pengajuan_id'=>1,'judul'=>'Pengajuan Masuk Antrian Admin','pesan'=>'Terdapat pengajuan baru yang menunggu penilaian SPK KPR.','tipe'=>'info','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-05 15:00:00'],
            ['user_id'=>7,'pengajuan_id'=>2,'judul'=>'Pengajuan Masuk Antrian Admin','pesan'=>'Terdapat pengajuan baru yang menunggu penilaian SPK KPR.','tipe'=>'info','dibaca'=>false,'tgl_dibaca'=>null,'created_at'=>'2024-06-06 16:30:00'],
        ]);
    }
}